repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--pretty, --ignore-missing-imports, --disallow-untyped-calls, --disallow-untyped-defs,
               --disallow-incomplete-defs, --check-untyped-defs, --disallow-untyped-decorators]
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: pep257